In [147]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [148]:
df = pd.read_csv(r"C:\Users\Hp\Desktop\ML Batch\Class 7\test_Loan_Pred - 1739709327694.csv")

In [149]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    object
 1   Gender             356 non-null    object
 2   Married            367 non-null    object
 3   Dependents         357 non-null    object
 4   Education          367 non-null    object
 5   Self_Employed      344 non-null    object
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB

In [151]:
df.isna().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [152]:
cat_col = ['Gender' , 'Dependents' , 'Self_Employed' ,'Loan_Amount_Term' ,'Credit_History']

for i in cat_col:
    print(i)
    val = df[i].mode().values[0]
    df[i] = df[i].fillna(val)

Gender
Dependents
Self_Employed
Loan_Amount_Term
Credit_History

In [153]:
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           5
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [154]:
df['LoanAmount'].fillna(df['LoanAmount'].median() , inplace = True)

In [155]:
import warnings
warnings.filterwarnings('ignore')

In [156]:
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

#### Conversion Categorigal col to numerical col

In [158]:
# we are using the saved file so that the model give the same pred/labels as before

mapping_df = pd.read_csv('mapping_dict_train.csv')

In [159]:
mapping_df

            Cols  Values
0         Female       0
1           Male       1
2             No       0
3            Yes       1
4              0       0
5              1       1
6              2       2
7             3+       3
8       Graduate       0
9   Not Graduate       1
10         Rural       0
11     Semiurban       1
12         Urban       2
13             N       0
14             Y       1

In [160]:
mapping_dict = dict(mapping_df.values)

In [161]:
mapping_dict

{'Female': 0,
 'Male': 1,
 'No': 0,
 'Yes': 1,
 '0': 0,
 '1': 1,
 '2': 2,
 '3+': 3,
 'Graduate': 0,
 'Not Graduate': 1,
 'Rural': 0,
 'Semiurban': 1,
 'Urban': 2,
 'N': 0,
 'Y': 1}

In [162]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    object
 1   Gender             367 non-null    object
 2   Married            367 non-null    object
 3   Dependents         367 non-null    object
 4   Education          367 non-null    object
 5   Self_Employed      367 non-null    object
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         367 non-null    float64
 9   Loan_Amount_Term   367 non-null    float64
 10  Credit_History     367 non-null    float64
 11  Property_Area      367 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB

In [180]:
cat_col = ['Gender', 'Married','Dependents', 'Education', 'Self_Employed', 'Property_Area']

for i in cat_col:
    df[i] = df[i].apply( lambda x : mapping_dict[x] )
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,1,1,0,0,0,5720,0,110.0,360.0,1.0,2
1,LP001022,1,1,1,0,0,3076,1500,126.0,360.0,1.0,2
2,LP001031,1,1,2,0,0,5000,1800,208.0,360.0,1.0,2
3,LP001035,1,1,2,0,0,2340,2546,100.0,360.0,1.0,2
4,LP001051,1,0,0,1,0,3276,0,78.0,360.0,1.0,2

In [186]:
final_df = pd.DataFrame(df['Loan_ID'])
final_df.head()

    Loan_ID
0  LP001015
1  LP001022
2  LP001031
3  LP001035
4  LP001051

In [194]:
df = df.iloc[:,1:]
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,1,1,0,0,0,5720,0,110.0,360.0,1.0,2
1,1,1,1,0,0,3076,1500,126.0,360.0,1.0,2
2,1,1,2,0,0,5000,1800,208.0,360.0,1.0,2
3,1,1,2,0,0,2340,2546,100.0,360.0,1.0,2
4,1,0,0,1,0,3276,0,78.0,360.0,1.0,2

#### Load Train file Standard Scaler

In [197]:
import pickle

#### Standardisation of the Data

In [199]:
# we are going to use the saved std scaler

with open('./standard_scaler.pkl' , 'rb') as file:
    ss = pickle.load(file)

In [201]:
ss

StandardScaler()

In [203]:
x_ft = ss.transform(df)
x_ft = pd.DataFrame(x_ft)
x_ft.columns = df.columns

In [205]:
x_ft

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0.472343,0.728816,-0.737806,-0.528362,-0.392601,0.445102,-0.874587,-0.491002,0.273231,0.411733,1.223298
1,0.472343,0.728816,0.253470,-0.528362,-0.392601,-0.621960,0.049466,-0.203925,0.273231,0.411733,1.223298
2,0.472343,0.728816,1.244745,-0.528362,-0.392601,0.154526,0.234277,1.267341,0.273231,0.411733,1.223298
3,0.472343,0.728816,1.244745,-0.528362,-0.392601,-0.918994,0.693840,-0.670424,0.273231,0.411733,1.223298
4,0.472343,-1.372089,-0.737806,1.892641,-0.392601,-0.541244,-0.874587,-1.065154,0.273231,0.411733,1.223298
...,...,...,...,...,...,...,...,...,...,...,...
362,0.472343,0.728816,2.236021,1.892641,2.547117,-0.245421,0.220108,-0.437175,0.273231,0.411733,1.223298
363,0.472343,0.728816,-0.737806,-0.528362,-0.392601,-0.185288,-0.437818,-0.401290,0.273231,0.411733,1.223298
364,0.472343,-1.372089,-0.737806,-0.528362,-0.392601,-0.551737,0.353172,-0.203925,0.273231,0.411733,-0.047607
365,0.472343,0.728816,-0.737806,-0.528362,-0.392601,0.154526,0.599586,0.370227,0.273231,0.411733,-1.318513
366,0.472343,-1.372089,-0.737806,-0.528362,2.547117,1.849556,-0.874587,-0.706309,-2.522836,0.411733,-1.318513

#### Predicting the Final Data

In [208]:
with open('./best_model.pkl' , 'rb') as file:
    lr = pickle.load(file)

In [210]:
lr

LogisticRegression()

In [214]:
pred = lr.predict(x_ft)
pred

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [218]:
pred_df = pd.DataFrame(pred , columns = ['Loan_Status'] )
pred_df.head(4)

   Loan_Status
0            1
1            1
2            1
3            1

In [220]:
map_dict = {0:'N' , 1:'Y'}
pred_df['Loan_Status'] = pred_df['Loan_Status'].apply( lambda x : map_dict[x] )

In [224]:
pred_df.head()

  Loan_Status
0           Y
1           Y
2           Y
3           Y
4           Y

In [226]:
final_df.shape , pred_df.shape

((367, 1), (367, 1))

In [232]:
submit_df = pd.concat([final_df , pred_df ] , axis = 1)

In [234]:
submit_df

      Loan_ID Loan_Status
0    LP001015           Y
1    LP001022           Y
2    LP001031           Y
3    LP001035           Y
4    LP001051           Y
..        ...         ...
362  LP002971           Y
363  LP002975           Y
364  LP002980           Y
365  LP002986           Y
366  LP002989           Y

[367 rows x 2 columns]

In [236]:
submit_df.to_csv('Final_Submission.csv' , index = False )